language: scala
jdk:
  # see https://github.com/travis-ci/travis-cookbooks/issues/35
  - oraclejdk7
scala:
  - 2.10.0-RC1
before_install:
  - sudo dpkg -r sbt
  - sudo rm /usr/bin/sbt
  - wget http://files.travis-ci.org/packages/deb/sbt/sbt-0.12.1.deb -O /tmp/sbt.deb
  - sudo dpkg -i /tmp/sbt.deb
  # - PLAY_VERSION="2-TLS-`git log -n 1 --pretty=format:%H`"
# script: play-${PLAY_VERSION}/play test
script: ./framework/runtests
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false
